version: '3.7'

services:
  ngnix:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    expose:
      - "8000"
    volumes:
      - static:/static

volumes:
  static:
  
    
