version: "3.9"

services:
  nginx:
    build:
      context: ./
      dockerfile: ./deployment/nginx/Dockerfile
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - passgen-djangocorn

  passgen-djangocorn:
    build:
      context: ./
      dockerfile: ./deployment/django/Dockerfile
    expose:
      - "8000"
    volumes:
      - static:/app/src/static

volumes:
  static:
  
    
